trigger:
- master

resources:
- repo: self

variables:
  tag: 63
  #'$(Build.BuildId)'
  

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: |
    #       $(tag)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy image
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-master-account-service-connection'
        regionName: 'ap-south-1'
        arguments: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        scriptType: 'inline'
        inlineScript: |
          sudo pip install setuptools
          sudo pip install wheel
          sudo pip install awscli --upgrade
          
          #Kubectl
          sudo curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          
          #AWS Configuration
          aws configure set aws-access-key $(AWS.AccessKeyID) 
          aws configure set aws_secret_access_key $(AWS.SecretAccessKey)
          aws eks --region ap-south-1 update-kubeconfig --name=eks_cluster_tuto
          
          #Apply
          kubectl delete -f $1
          sleep 15
          kubectl apply -f $1
    # - task: AWSCLI@1
    #   inputs:
    #     awsCredentials: 'aws-master-account-service-connection'
    #     regionName: 'ap-south-1'
    #     awsCommand: 'eks'
    #     awsSubCommand: 'update-kubeconfig'
    #     awsArguments: '--name eks_cluster_tuto'
    #     failOnStandardError: true
    
    # - task: KubernetesManifest@0
    #   inputs:
    #     action: 'deploy'
    #     kubernetesServiceConnection: 'aws-kubernetes-cluster-service-connection'
    #     manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
    #     containers: 'changa2127/currency-exchange-devops:63'