trigger:
- master

resources:
- repo: self

variables:
  tag: 63
  #'$(Build.BuildId)'
  

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: |
    #       $(tag)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy image
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'
    - task: AWSCLI@1
      inputs:
        awsCredentials: 'aws-master-account-service-connection'
        regionName: 'ap-south-1'
        awsCommand: 'eks --region ap-south-1 update-kubeconfig --name=eks_cluster_tuto'
        #awsSubCommand: 'aws eks --region ap-south-1 update-kubeconfig --name=eks_cluster_tuto'
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        #kubernetesServiceConnection: 'aws-kubernetes-cluster-service-connection'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        containers: changa2127/currency-exchange-devops:$(tag)